---

- name: Create system user for node_exporter
  user:
    name: "{{ node_user }}"
    shell: /bin/false
    create_home: no
    state: present

- name: Install node exporter
  unarchive:
    src: "{{ node_exporter }}"
    dest: /tmp/
    remote_src: yes

- name: Move node_exporter to the binaris
  copy:
    src: "/tmp/{{ node_version}}.linux-amd64/node_exporter"
    dest: "{{ node_bin }}"
    owner: root
    group: root
    mode: 0755
    remote_src: yes

- name: Install service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: "{{ node_user }}"
    group: "{{ node_group }}"
  notify:
    - Reload systemd daemon
    - start and enable

- name: Remove node_exporter directory
  file:
    path: "/tmp/{{ node_version }}.linux-amd64"
    state: absent
