---
- name: Reload systemd daemon
  systemd_service:
    daemon_reload: true

- name: start and enable
  systemd:
    name: prometheus
    state: started
    enabled: yes

- name: restart
  systemd:
    name: prometheus
    state: restarted